before_script:
  - apt-get update
  - apt-get install -y python-dev
  - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
  - python get-pip.py
  - pip install ansible
  - git clone https://github.com/Juniper/ansible-junos-stdlib.git roles/Juniper.junos

#################################################
## Execute TEST Stage on all branches          ##
#################################################
check_playbooks:
  stage: test
  script:
    - ansible-playbook pb.conf.all.yaml --syntax-check
    - ansible-playbook pb.check.overlay.yaml --syntax-check
    - ansible-playbook pb.check.underlay.yaml --syntax-check

#################################################
## Execute DEPLOY Stage only on Branch Master  ##
#################################################
deploy_config:
  stage: deploy
  only:
    - master
  script:
    - ansible-playbook pb.conf.all.yaml
