---
############################################################
- name: Create and apply configuration for Leaf QFX / L2
  hosts: saimspine
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - overlay-evpn-qfx-l3
