---

- include: pb.init.make_clean.yaml

############################################################
- name: Create and apply configuration for Leaf QFX / L2
  hosts: saimleaf
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-qfx-l2
    - build-config

############################################################
- name: Create and apply configuration for Leaf QFX / L3
  hosts: saimspine
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-qfx-l3
    - build-config
