---
- name: Generate variables
  hosts: [saimleaf,saimspine]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  vars:
    generate_p2p:
      nbr_networks: 15
      network_size: 31
      network_pool: 192.168.0.0/24
    generate_tenant:
      nbr_tenant: 2
      nbr_vni_tenant: 5
      tenant_start_id: 50
      vlan_start: 200
      vni_prefix: 5
      network_pool: 10.0.0.0/16
      network_size: 24
  roles:
    - generate-p2p-ips
    - generate-tenant-vni

- name: Generate variables for underlay
  hosts: [saimleaf,saimspine]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
    - include_vars: "group_vars/all/generated_p2p_ips.yaml"
  roles:
    - generate-underlay-bgp
