---
- name: Generate variables
  hosts: [saimleaf,saimspine]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  vars:
  roles:
    - generate-p2p-ips
    - generate-tenant-vni

- name: Generate variables for underlay
  hosts: [saimleaf,saimspine]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - generate-underlay-bgp
