---
- name: Ensures dir exists
  file: path={{ build_dir }}/ state=directory

- name: Building underlay configuration with EBGP
  template: >
    src=main.conf.j2
    dest={{ build_dir }}/underlay-ebgp.conf.part
