
underlay:
  mtu_phy_int: 9192
  mtu_logical_int: 9000
  network_size: 31
  bfd:
    min_interval: 350
    multiplier: 3
    mode: automatic
  networks:
    loopbacks: 10.0.0.0/8
    underlay: 192.168.0.0/16
