---
- name: Ensures dir exists
  file: path=group_vars/all state=directory

- name: Generate P2P IPs
  template: >
    src=main.conf.j2
    dest=group_vars/all/generated-intermediate-loopbacks.yaml
  run_once: true
